version: '3'
services:  
  auth-pruebas:
    image: pagos-auth
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    ports:
        - 8081:80
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - TZ=America/Tegucigalpa
